# Generated by Django 4.0 on 2023-06-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_publicmember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='PublicMember',
        ),
    ]
