# Generated by Django 5.1.5 on 2025-01-31 03:17

import django.db.models.deletion
import imagekit.models.fields
import news.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_pt', models.CharField(blank=True, max_length=50, null=True)),
                ('name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('name_seo_tt', models.CharField(blank=True, max_length=100, null=True)),
                ('name_seo_pt', models.CharField(blank=True, max_length=100, null=True)),
                ('name_seo_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Tetum', 'Tetum'), ('Portugues', 'Portugues'), ('English', 'English')], max_length=10, null=True, verbose_name='Lingua')),
                ('title', models.CharField(max_length=300, verbose_name='Titulu Nutisia (Tetum)')),
                ('title_seo', models.CharField(blank=True, max_length=350, null=True, verbose_name='Titulu Seo (Tetum)')),
                ('headline', models.TextField(null=True, verbose_name='Sinopsiu Tetum')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Konteudu Tetum')),
                ('place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fatin')),
                ('date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_headline', models.BooleanField(blank=True, default=False, null=True)),
                ('is_main', models.BooleanField(blank=True, default=False, null=True)),
                ('hits', models.IntegerField(blank=True, default=0, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newscat', verbose_name='kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_tt', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_pt', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_en', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(null=True, upload_to=news.utils.upload_img, verbose_name='Upload Imajen')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsimage', to='news.news')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
