# Generated by Django 5.1.5 on 2025-01-31 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscat',
            name='name_seo_pt',
        ),
        migrations.RemoveField(
            model_name='newscat',
            name='name_seo_tt',
        ),
    ]
