# Generated by Django 5.1.5 on 2025-01-31 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newscat_name_seo_pt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscat',
            old_name='name_seo_en',
            new_name='slug_name_en',
        ),
    ]
