# Generated by Django 5.1.5 on 2025-01-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_name_seo_en_newscat_slug_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscat',
            name='name_seo_tt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
