# Generated by Django 5.1.5 on 2025-01-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newscat_name_seo_tt'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscat',
            name='name_seo_pt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
