# Generated by Django 5.1.5 on 2025-01-31 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newscat_name_seo_pt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscat',
            old_name='name',
            new_name='name_tt',
        ),
    ]
