# Generated by Django 5.1.5 on 2025-01-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_name_newscat_name_tt'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Titulu Nutisia (English)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_pt',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Titulu Nutisia (Portugues)'),
        ),
    ]
