# Generated by Django 5.1.5 on 2025-01-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_title_en_news_title_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Konteudu English'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Konteudu Portugues'),
        ),
        migrations.AddField(
            model_name='news',
            name='headline_en',
            field=models.TextField(null=True, verbose_name='Sinopsiu English'),
        ),
        migrations.AddField(
            model_name='news',
            name='headline_pt',
            field=models.TextField(null=True, verbose_name='Sinopsiu Portugues'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_seo_en',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Titulu Seo (Tetum)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_seo_pt',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Titulu Seo (Tetum)'),
        ),
    ]
