# Generated by Django 5.1.5 on 2025-01-31 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_content_en_news_content_pt_news_headline_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscat',
            old_name='slug_name_en',
            new_name='name_seo_en',
        ),
    ]
