# Generated by Django 5.1.5 on 2025-01-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_slug_name_en_newscat_name_seo_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscat',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newscat',
            name='slug_pt',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newscat',
            name='slug_tt',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
