# Generated by Django 5.1.5 on 2025-01-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newscat_slug_en_newscat_slug_pt_newscat_slug_tt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscat',
            name='slug_tt',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
