# Generated by Django 5.1.5 on 2025-01-31 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_newscat_slug_tt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscat',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='newscat',
            name='slug_pt',
        ),
        migrations.RemoveField(
            model_name='newscat',
            name='slug_tt',
        ),
    ]
