# Generated by Django 5.1.5 on 2025-01-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_remove_newscat_slug_en_remove_newscat_slug_pt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscat',
            name='name_tt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
