# Generated by Django 5.1.5 on 2025-01-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_newscat_name_tt'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscat',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newscat',
            name='slug_pt',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newscat',
            name='slug_tt',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
