# Generated by Django 5.1.5 on 2025-01-31 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_newscat_slug_en_newscat_slug_pt_newscat_slug_tt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscat',
            name='name_seo_en',
        ),
        migrations.RemoveField(
            model_name='newscat',
            name='name_seo_pt',
        ),
        migrations.RemoveField(
            model_name='newscat',
            name='name_seo_tt',
        ),
    ]
