# Generated by Django 5.1.5 on 2025-01-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_remove_newscat_name_seo_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscat',
            old_name='slug_en',
            new_name='slug_name_en',
        ),
        migrations.RenameField(
            model_name='newscat',
            old_name='slug_pt',
            new_name='slug_name_pt',
        ),
        migrations.RenameField(
            model_name='newscat',
            old_name='slug_tt',
            new_name='slug_name_tt',
        ),
    ]
