# Generated by Django 5.1.5 on 2025-01-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_rename_slug_en_newscat_slug_name_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='content_tt',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='headline',
            new_name='headline_tt',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_tt',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_seo',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_seo_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_seo_pt',
        ),
        migrations.AddField(
            model_name='news',
            name='slug_name_en',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Titulu Seo (English)'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_name_pt',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Titulu Seo (Portugues)'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_name_tt',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Titulu Seo (Tetum)'),
        ),
    ]
