# Generated by Django 5.1.5 on 2025-01-31 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_rename_content_news_content_tt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='slug_name_en',
            new_name='slug_title_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='slug_name_pt',
            new_name='slug_title_pt',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='slug_name_tt',
            new_name='slug_title_tt',
        ),
    ]
