# Generated by Django 5.1.5 on 2025-01-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_rename_slug_name_en_news_slug_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug_title_en',
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True, verbose_name='Titulu Seo (English)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug_title_pt',
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True, verbose_name='Titulu Seo (Portugues)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug_title_tt',
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True, verbose_name='Titulu Seo (Tetum)'),
        ),
    ]
