# Generated by Django 5.1.5 on 2025-01-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_alter_news_slug_title_en_alter_news_slug_title_pt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug_title_en',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Titulu Seo (English)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug_title_pt',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Titulu Seo (Portugues)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug_title_tt',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True, verbose_name='Titulu Seo (Tetum)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulu Nutisia (English)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_pt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulu Nutisia (Portugues)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_tt',
            field=models.CharField(max_length=200, verbose_name='Titulu Nutisia (Tetum)'),
        ),
    ]
