def lang_master(lang):
    lang_data = []
    if lang == "tt":
        lang_data = {
            "LBL_MIN_NAME": "Ministeriu Obras Publika",
            "LBL_MIN_CODE": "MOP",
            "TITLE_NEWS": "Notisia",
            "LBL_PARTNER": "Parceiru Dezenvolvimentu",
            "LBL_PUBLIC": "Publiku",
            "LBL_LOCAL": "Lokal",
            "LBL_IMG": "Imagen",
            "LBL_PHONE": "Telemovel",
            "LBL_ADDRESS": "Enderesu",
            "LBL_CONTACT": "Kontaktu",
            "LBL_MUN": "Municipiu",
            "LBL_OTHER_INFO": "Informasaun seluk",
            "LBL_OTHER_INFO2": "Laiha informasaun no vaga",
            "LBL_LINK_EXTERNAL": "Links Externa",
            "LBL_OTHER_SYSTEM": "Aplikasaun seluk",
            "LBL_SOCIAL": "Redes Social",
            "LBL_DESIGN_BY": "Desenvolve husi",
            "LBL_RESPONSIBLE": "Responsavel",
            "LBL_ARCHIVE": "Arkivu Nutisia",
            "LBL_MORE": "Mais",
            "LBL_ORGCHART": "Organograma",
            
            "LINK_PSTATUS": "Status Projetu",
            "LINK_PNEW": "Projetu Foun",
            "LINK_PROLL": "Reaproriasaun",
            "LINK_PCOMP": "Kompletu",
            "LINK_PONGOING": "Lao Hela",
            "LINK_PNOTSTART": "Seidauk Hahu",
            "LINK_PSUM": "Sumariu Projetu",
            "LBL_PCAT": "Kategoria Projetu",
            "LBL_PMUN": "Projetu iha Municipiu",
            "LBL_PCAP": "Capital Projetu",
            "LBL_PSEC": "Sector Projetu",
            "LINK_PREPORT": "Relatoriu Projetu",
            "LINK_PMAPG": "Mapa do Projetu",
            "LINK_PMAPS": "Mapa Status Projetu",
            "LINK_PMAPP": "Mapa Progresu Projetu",
            "LINK_PLIST": "Lista Projetu Lao Hela",
            "LINK_PHIST": "Lista Projetu Kompletu",
        }
    elif lang == "pt":
        lang_data = {
            "LBL_MIN_NAME": "Ministério das Obras Públicas",
            "LBL_MIN_CODE": "MOP",
            "TITLE_NEWS": "Notícias",
            "LBL_PARTNER": "Parceiros Desenvolvimento",
            "LBL_PUBLIC": "Público",
            "LBL_LOCAL": "Local",
            "LBL_IMG": "Imagens",
            "LBL_PHONE": "Telemovel",
            "LBL_ADDRESS": "Endereço",
            "LBL_CONTACT": "Contacto",
            "LBL_MUN": "Município",
            "LBL_OTHER_INFO": "Outra informação",
            "LBL_OTHER_INFO2": "sem vaga ou competição",
            "LBL_LINK_EXTERNAL": "Links Externos",
            "LBL_OTHER_SYSTEM": "Outros Aplicativos",
            "LBL_SOCIAL": "Redes Sociais",
            "LBL_DESIGN_BY": "Desenvolvido por",
            "LBL_RESPONSIBLE": "Responsável",
            "LBL_ARCHIVE": "Arquiva Notícias",
            "LBL_MORE": "Mais",
            "LBL_ORGCHART": "Organograma",
            
            "LINK_PSTATUS": "Estado do Projetos",
            "LINK_PNEW": "Projeto de",
            "LINK_PROLL": "Reapropriação",
            "LINK_PCOMP": "Completo",
            "LINK_PONGOING": "Ongoing",
            "LINK_PNOTSTART": "Not Started",
            "LINK_PSUM": "Sumário Projeto",
            "LBL_PCAT": "Categoria Projetos",
            "LBL_PMUN": "Projeto em Municípios",
            "LBL_PCAP": "Capital Projeto",
            "LBL_PSEC": "Sector Projeto",
            "LINK_PREPORT": "Relatório Projeto",
            "LINK_PMAPG": "Mapa do Projeto",
            "LINK_PMAPS": "Mapa do Estado do Projeto",
            "LINK_PMAPP": "Mapa do Progresso do Projeto",
            "LINK_PLIST": "Lista dos Projetos em Andamento",
            "LINK_PHIST": "Lista dos Projeto Completido",
        }
    elif lang == "en":
        lang_data = {
            "LBL_MIN_NAME": "Ministery of Public Works",
            "LBL_MIN_CODE": "MOP",
            "TITLE_NEWS": "News",
            "LBL_PARTNER": "Development Partnership",
            "LBL_PUBLIC": "Public",
            "LBL_LOCAL": "Local",
            "LBL_IMG": "Images",
            "LBL_PHONE": "Phone",
            "LBL_ADDRESS": "Address",
            "LBL_CONTACT": "Contact",
            "LBL_MUN": "Municipality",
            "LBL_OTHER_INFO": "Others Information",
            "LBL_OTHER_INFO2": "no vacancy or competition",
            "LBL_LINK_EXTERNAL": "External Links",
            "LBL_OTHER_SYSTEM": "Other Application",
            "LBL_SOCIAL": "Social Network",
            "LBL_DESIGN_BY": "Developed by",
            "LBL_RESPONSIBLE": "Responsible",
            "LBL_ARCHIVE": "News Archive",
            "LBL_MORE": "More",
            "LBL_ORGCHART": "Org. Chart",

            "LINK_PSTATUS": "Project Status",
            "LINK_PNEW": "New Project of",
            "LINK_PROLL": "Roll Over",
            "LINK_PCOMP": "Completed",
            "LINK_PONGOING": "Ongoing",
            "LINK_PNOTSTART": "Not Started",
            "LINK_PSUM": "Project Summary",
            "LBL_PCAT": "Project Category",
            "LBL_PMUN": "Project by Municipality",
            "LBL_PCAP": "Project Capital",
            "LBL_PSEC": "Project Sector",
            "LINK_PREPORT": "Project Reports",
            "LINK_PMAPG": "Project Map",
            "LINK_PMAPS": "Map of Project Status",
            "LINK_PMAPP": "Map of Project Progress",
            "LINK_PLIST": "List of Ongoing Projects",
            "LINK_PHIST": "List of Completed Projects",
        }
    # lang_data.append([LANG_NEWS])
    return lang_data