# Generated by Django 5.1.5 on 2026-04-18 04:45

import django.core.validators
import django.db.models.deletion
import pub.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Tetum', 'Tetum'), ('Portugues', 'Portugues'), ('English', 'English')], max_length=10, null=True, verbose_name='Lingua')),
                ('title', models.CharField(max_length=300, null=True)),
                ('desc', models.CharField(max_length=300, null=True)),
                ('file', models.FileField(upload_to=pub.utils.upload_pub, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('image', models.ImageField(upload_to=pub.utils.upload_pub, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Tetum', 'Tetum'), ('Portugues', 'Portugues'), ('English', 'English')], max_length=10, null=True, verbose_name='Lingua')),
                ('title', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=pub.utils.upload_tender, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('image', models.ImageField(upload_to=pub.utils.upload_tender, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Tetum', 'Tetum'), ('Portugues', 'Portugues'), ('English', 'English')], max_length=10, null=True, verbose_name='Lingua')),
                ('title', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=pub.utils.upload_vaga, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('image', models.ImageField(upload_to=pub.utils.upload_vaga, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
