# Generated by Django 5.1.5 on 2026-04-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0002_rename_date_tender_closing_date_remove_tender_hashed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_tt', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
