# Generated by Django 5.1.5 on 2026-04-18 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0003_tendercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pub.tendercategory'),
            preserve_default=False,
        ),
    ]
