# Generated by Django 5.1.5 on 2026-04-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0004_alter_tender_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendercategory',
            name='name_pt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
