# Generated by Django 5.1.5 on 2026-04-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0005_tendercategory_name_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='hashed',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
