# Generated by Django 4.0 on 2023-03-23 02:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import doc.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tt', models.CharField(blank=True, max_length=20, null=True)),
                ('name_pt', models.CharField(blank=True, max_length=20, null=True)),
                ('name_en', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Tetum', 'Tetum'), ('Portugues', 'Portugues'), ('English', 'English')], max_length=10, null=True, verbose_name='Lingua')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=doc.utils.upload_doc, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('doc_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.doctype', verbose_name='Tipu Dokumentu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
