# Generated by Django 4.0 on 2023-04-01 00:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import doc.utils


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Tetum', 'Tetum'), ('Portugues', 'Portugues'), ('English', 'English')], max_length=10, null=True, verbose_name='Lingua')),
                ('title', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=doc.utils.upload_report, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('image', models.ImageField(upload_to=doc.utils.upload_report, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
