# Generated by Django 3.2 on 2023-06-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_auto_20230618_0433'),
        ('doc', '0003_reportowner_report_owner'),
    ]

    operations = [
    ]
