# Generated by Django 4.0 on 2023-03-23 02:22

from django.db import migrations, models
import django.db.models.deletion
import multimedia.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_tt', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_pt', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_en', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to=multimedia.utils.upload_album, verbose_name='Upload Imajen')),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tt', models.CharField(max_length=20, null=True)),
                ('name_pt', models.CharField(blank=True, max_length=20, null=True)),
                ('name_en', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_tt', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_pt', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_en', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to=multimedia.utils.upload_gallery, verbose_name='Upload Imajen')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='multimedia.album', verbose_name='Album')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc_tet', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_pt', models.CharField(blank=True, max_length=200, null=True)),
                ('desc_en', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='banner_default.jpg', null=True, upload_to=multimedia.utils.upload_banner, verbose_name='Upload Imajen')),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('attr', models.CharField(blank=True, choices=[('', ''), ('active', 'active')], max_length=6, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multimedia.imagecat', verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
