# Generated by Django 4.0 on 2023-03-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='desc_tet',
            new_name='desc_tt',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='hashed',
        ),
    ]
