# Generated by Django 4.0 on 2023-03-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('multimedia', '0002_rename_desc_tet_banner_desc_tt_remove_banner_hashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Tetum', 'Tetum'), ('Portugues', 'Portugues'), ('English', 'English')], max_length=10, null=True, verbose_name='Lingua')),
                ('source', models.CharField(choices=[('Youtube', 'Youtube'), ('Facebook', 'Facebook')], max_length=10, null=True, verbose_name='Source')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('embed_url', models.TextField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
