# Generated by Django 5.1.5 on 2025-01-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('abrev', models.CharField(max_length=2, null=True)),
                ('icon_lang', models.ImageField(blank=True, upload_to='icon_languagues')),
            ],
            options={
                'verbose_name_plural': 'Icon Lingua',
            },
        ),
    ]
