# Generated by Django 5.1.5 on 2025-01-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languague',
            name='icon_lang',
            field=models.ImageField(blank=True, null=True, upload_to='icon_languagues'),
        ),
    ]
