# Generated by Django 4.0 on 2023-03-23 13:53

import announce.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=announce.utils.upload),
        ),
    ]
