# Generated by Django 4.0 on 2023-03-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0002_announce_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announce',
            name='is_publish',
        ),
    ]
