# Generated by Django 4.0 on 2023-04-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0003_remove_announce_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
