# Generated by Django 3.2.9 on 2023-01-10 16:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_tet', models.CharField(max_length=300, null=True)),
                ('description_por', models.CharField(blank=True, max_length=300, null=True)),
                ('description_eng', models.CharField(blank=True, max_length=300, null=True)),
                ('file', models.FileField(upload_to=project.utils.upload_proj_map, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['js'])], verbose_name='Upload .js file')),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('is_sent', models.BooleanField(default=False, null=True)),
                ('is_approved', models.BooleanField(default=True, null=True)),
                ('entered_date', models.DateTimeField(null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(max_length=32)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapdata_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Aprova husi')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapdata_entered_by', to=settings.AUTH_USER_MODEL, verbose_name='Upload husi')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_tet', models.CharField(max_length=300, null=True)),
                ('description_por', models.CharField(blank=True, max_length=300, null=True)),
                ('description_eng', models.CharField(blank=True, max_length=300, null=True)),
                ('file', models.FileField(upload_to=project.utils.upload_proj_map, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to=project.utils.upload_proj_map, verbose_name='Imaje')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_sent', models.BooleanField(default=False, null=True)),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('entered_date', models.DateTimeField(null=True)),
                ('approved_date', models.DateTimeField(null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pd_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pd_entered_by', to=settings.AUTH_USER_MODEL, verbose_name='Entered by')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.municipality')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.year')),
            ],
        ),
    ]
