# Generated by Django 4.0 on 2023-03-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('new', models.IntegerField(blank=True, default=0, null=True)),
                ('rollover', models.IntegerField(blank=True, default=0, null=True)),
                ('completed', models.IntegerField(blank=True, default=0, null=True)),
                ('ongoing', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='projectdata',
            name='year',
        ),
        migrations.RemoveField(
            model_name='projectmapdata',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='projectmapdata',
            name='entered_by',
        ),
        migrations.DeleteModel(
            name='ProjectOwner',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='ProjectData',
        ),
        migrations.DeleteModel(
            name='ProjectMapData',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
