# Generated by Django 4.0 on 2023-03-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_cap_cat_sec_projsec_projcat_projcap'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalhome',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projcap',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projcat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projsec',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
