# Generated by Django 4.0 on 2023-03-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_portalhome_is_active_projcap_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projcap',
            name='cap',
        ),
        migrations.RemoveField(
            model_name='projsec',
            name='sec',
        ),
        migrations.RenameField(
            model_name='projcat',
            old_name='total',
            new_name='emer',
        ),
        migrations.RemoveField(
            model_name='projcat',
            name='cat',
        ),
        migrations.AddField(
            model_name='projcat',
            name='fi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projcat',
            name='lm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Cap',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='ProjCap',
        ),
        migrations.DeleteModel(
            name='ProjSec',
        ),
        migrations.DeleteModel(
            name='Sec',
        ),
    ]
