# Generated by Django 4.0 on 2023-03-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_projcap_cap_remove_projsec_sec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs', models.IntegerField(blank=True, null=True)),
                ('cm', models.IntegerField(blank=True, null=True)),
                ('cd', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrada', models.IntegerField(blank=True, null=True)),
                ('ponte', models.IntegerField(blank=True, null=True)),
                ('cheias', models.IntegerField(blank=True, null=True)),
                ('urban', models.IntegerField(blank=True, null=True)),
                ('estudu', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
