# Generated by Django 4.0 on 2023-04-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projcap_projsec'),
    ]

    operations = [
        migrations.AddField(
            model_name='projsec',
            name='asset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
