# Generated by Django 4.0 on 2023-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projsec_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalhome',
            name='notstarted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
