# Generated by Django 4.0 on 2023-04-02 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0008_portalhome_notstarted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjMapS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True, verbose_name='Titulu')),
                ('file', models.FileField(upload_to=project.utils.upload_proj_map, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['js'])], verbose_name='Upload file .js')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProjMapG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True, verbose_name='Titulu')),
                ('file', models.FileField(upload_to=project.utils.upload_proj_map, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['js'])], verbose_name='Upload file .js')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
