# Generated by Django 4.0 on 2023-06-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_projmapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjMopCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est', models.IntegerField(blank=True, null=True)),
                ('r4d', models.IntegerField(blank=True, null=True)),
                ('emer', models.IntegerField(blank=True, null=True)),
                ('obrassel', models.IntegerField(blank=True, null=True)),
                ('menor', models.IntegerField(blank=True, null=True)),
                ('bsgsm', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
