# Generated by Django 4.0 on 2023-03-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='contactmun',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='contactmun',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='contactmun',
            old_name='person',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactmun',
            name='hashed',
        ),
        migrations.RemoveField(
            model_name='contactmun',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hashed',
        ),
        migrations.AddField(
            model_name='contactmun',
            name='mun',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Municipiu'),
        ),
    ]
