# Generated by Django 4.0 on 2023-03-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
        ('about', '0002_delete_contactus_rename_latitude_contact_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmun',
            name='mun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.municipality', verbose_name='Municipiu'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='div',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.division', verbose_name='Diresaun'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='person.jpg', null=True, upload_to='orgchart/', verbose_name='Imajen'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Naran'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.position', verbose_name='Pojisaun'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(blank=True, choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=4, null=True, verbose_name='Sexu'),
        ),
    ]
