# Generated by Django 4.0 on 2023-03-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_contactmun_mun_alter_employee_div_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
