# Generated by Django 4.0 on 2023-03-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('custom', '0001_initial'),
        ('about', '0004_employee_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Structure',
        ),
    ]
