# Generated by Django 4.0 on 2023-04-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
