# Generated by Django 4.0 on 2023-06-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_structure_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
    ]
