# Generated by Django 4.0 on 2023-06-15 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_remove_contact_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lng',
        ),
    ]
