# Generated by Django 4.0 on 2023-06-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_remove_contact_lat_remove_contact_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='hist_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='hist_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='hist_tt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
