# Generated by Django 4.0 on 2023-07-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_about_hist_en_about_hist_pt_about_hist_tt'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
