# Generated by Django 4.0 on 2023-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name_tt', models.CharField(blank=True, max_length=50, null=True)),
                ('name_pt', models.CharField(blank=True, max_length=50, null=True)),
                ('name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_tt', models.TextField(blank=True, null=True)),
                ('desc_pt', models.TextField(blank=True, null=True)),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dg',
            name='desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dg',
            name='desc_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dg',
            name='desc_tt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='desc_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='desc_tt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
