# Generated by Django 4.0 on 2023-06-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_alter_dg_name_en_alter_dg_name_pt_alter_dg_name_tt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orgchart/', verbose_name='Organograma'),
        ),
        migrations.AddField(
            model_name='division',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orgchart/', verbose_name='Organograma'),
        ),
        migrations.AddField(
            model_name='otherdiv',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='others/', verbose_name='Upload Logo'),
        ),
    ]
