# Generated by Django 4.0 on 2023-06-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_dg_image_division_image_otherdiv_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdiv',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
