# Generated by Django 4.0 on 2023-06-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_otherdiv_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdiv',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='otherdiv',
            name='website',
        ),
    ]
