# Generated by Django 4.0 on 2023-07-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_remove_otherdiv_facebook_remove_otherdiv_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name_pt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name_tt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
